

networks:
  Inception:

volumes:
  db_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: "/home/omar/Data/mariadbData"
    #   o: bind
  wp_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: "/home/omar/Data/wordpressData"
    #   o: bind

services:
  nginx:
    build:
      context: "./requirement/nginx"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - Inception
    ports:
      - 443:443
    env_file:
      - .env
    restart: always
  wordpress:
    build:
      context: "./requirement/wordpress"
    volumes:
      - wp_data:/var/www/html
    networks:
      - Inception
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
      - redis
  mariadb:
    build:
      context: "./requirement/MariaDB"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - Inception
    env_file:
      - .env
    restart: always
  redis:
    build:
      context: "./requirement/bonus/redis"
    networks:
      - Inception
    env_file:
      - .env
    restart: always
  adminer:
    build:
      context: "./requirement/bonus/adminer"
    networks:
      - Inception
    env_file:
      - .env
    restart: always
  ftp:
    build:
      context: "./requirement/bonus/ftp"
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - Inception
    env_file:
      - .env
    restart: always
  static_website:
    build:
      context: "./requirement/bonus/static_website"
    ports:
      - "80:80"
    networks:
      - Inception
    env_file:
      - .env
    restart: always
