

networks:
  Inception:
    ipam:
      driver: default
      # config:
      #   - subnet: "192.168.92.21"


volumes:
  db_data:
    driver: local
    driver_opts:
      # type: none
      device: "/home/omar/Data/mariadbData"
    #   o: bind
  wp_data:
    driver: local
    driver_opts:
      # type: none
      device: "/home/omar/Data/wordpressData"
      # o: bind
  

services:
  nginx:
    build:
      context: "./requirement/nginx"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - Inception
    ports:
      - 443:443
    env_file:
      - .env
    restart: always
  wordpress:
    build:
      context: "./requirement/wordpress"
    volumes:
      - wp_data:/var/www/html
    networks:
      - Inception
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
      - redis
  mariadb:
    build:
      context: "./requirement/MariaDB"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - Inception
    env_file:
      - .env
    restart: always
  redis:
    build:
      context: "./requirement/bonus/redis"
    networks:
      - Inception
    env_file:
      - .env
    restart: always


