version: '3.8'

services:
  nginx:
    volumes:
        - wp_data:/var/www/html
    networks:
      - Inception
    ports:
      - 443:443
    env_file:
      - .env
    restart: always
  wordpress:
    volumes:
      - wp_data:/var/www/html
    networks:
      - Inception
    env_file:
      - .env
    restart: always
volumes:    
  db_data:
    driver: ~/Descktop/
  wp_data:
    driver: ~/Descktop/
networks:
  Inception:
  ipam:
    driver: default
    config:
      - subnet: "192.168.92.21"

    